{% set name = "delimited-protobuf" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4239393c4b8e3c89587e016424d1f404bc482db41972febfe7aefd9a38ccbf4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - protobuf

test:
  imports:
    - delimited_protobuf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/soulmachine/delimited-protobuf
  license: Apache-2.0
  license_file: LICENSE
  summary: A read/write library for length-delimited protobuf messages

extra:
  recipe-maintainers:
    - soulmachine
